### ISSUE TITLE
SMS integration with Hoiio

### ISSUE THREAD

**Issue by laurenceputra** [iamtalented/website#12]
## User story

As a student, I should receive an sms with a link to change my courses when I sign up
## SMS Provider

Hoiio has kindly agreed to sponsor sms credits for our sign up process.
## Acceptance Criteria

When a student signs up, he/she should receive an SMS similar to the template below

> You have signed up for
> Photography for David's birthday party
> Singing David's birthday song
> Dancing for David's birthday party
> 
> If you want to change your options, head over to http://bit.ly/asdasd to change it. The link will expire in 3 days.
## Tasks
- [ ] Generate unique urls for each sign up
- [ ] Shorten URLs with http://bit.ly
- [ ] Send out SMS with Hoiio
