### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by laurenceputra** [iamtalented/website#13]
## User story

As a student, I should be able to sign up for the courses through the website
## Acceptance Criteria

When a student visits the sign up page, he/she should be able to enter the following details which will then be saved on the backend.
- Name
- NRIC
- Phone number
- Email
- Course 1 [Dropdown]
- Course 2 [Dropdown]
- Course 3 [Dropdown]
- Checkbox requiring them to allow us to send them email/sms [PDPC]
## Tasks
- [ ] Create a new DB backend
- [ ] Create a Mongoose Model for students
- [ ] Create the form for students to submit
- [ ] Create validation checks (All fields required, phone/email is either or)

**Comment by laurenceputra** [comment]
Form for users to submit. Discussion on https://trello.com/c/mYbrswY8/17-data-to-collect-on-sign-up-page
